#!/usr/bin/env python
# Copyright (c) 2021 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

from __future__ import absolute_import, division, print_function

import DependencyRules as dr

dr.add(
   dr.Source( [ dr.Regex( '.*\.pb\.(h|cc)' ) ],
              buildRequires=( 'grpc', 'gRPC is used to generate these files ' ),
              skipDeps=( True, 'Generated by custom makefile rule' ) ),
   dr.Rpm( 'EosSdkRpcProtos',
           buildRequires=( [ 'GoExternal' ],
                           'Needed to satisfy dependencies protolock' )
   ),
   dr.Rpm( 'EosSdkRpcProtos-devel',
           buildRequires=( 'grpc-devel',
                           'gRPC headers for compiling the EosSdkRpcProtos'
                           'gRPC library.' )
   ),
)
