name: ci
on:
  push:
    branches:
      - develop # XXX
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install protobuf-compiler
        run: sudo apt install -y protobuf-compiler
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - name: install protoc-gen-doc
        run: go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
      - name: generate the api-reference.md file
        run: |
          protoc -I${{github.workspace}}/proto \
              --doc_out=${{github.workspace}}/docs/api-reference \
              --doc_opt=${{github.workspace}}/.github/templates/api-reference-md.tmpl,api-reference.md:EosSdkRpc.proto \
              ${{github.workspace}}/proto/*.proto
      - name: split api-reference.md into multiple files
        run: ${{github.workspace}}/.github/scripts/split-api-reference.sh ${{github.workspace}}/docs/api-reference
      - uses: actions/upload-artifact@v3
        with:
          name: api-reference
          path: ${{github.workspace}}/docs/api-reference/
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
